// Generates supabase/seed.sql from data/*.json.
// Usage: node scripts/build-seed.mjs
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const parts = JSON.parse(readFileSync(join(root, "data/parts.json"), "utf8"));
const designs = JSON.parse(readFileSync(join(root, "data/reference_designs.json"), "utf8"));

const s = (v) => `'${String(v).replace(/'/g, "''")}'`;
const arr = (a) => `ARRAY[${a.map(s).join(",")}]::text[]`;
const intArr = (a) => `ARRAY[${a.map(Number).join(",")}]::int[]`;

let sql = "-- Generated by scripts/build-seed.mjs. Do not edit by hand.\nbegin;\n\n";

for (const p of parts) {
  sql += `insert into parts (id,name,slot,brand,description,price_usd_approx,pack_size,mass_g,buy_url,tags,compat) values (${[
    s(p.id), s(p.name), s(p.slot), s(p.brand), s(p.description), p.price_usd_approx, p.pack_size, p.mass_g,
    s(p.buy_url), arr(p.tags), `${s(JSON.stringify(p.compat))}::jsonb`,
  ].join(",")})
on conflict (id) do update set name=excluded.name, slot=excluded.slot, brand=excluded.brand, description=excluded.description,
  price_usd_approx=excluded.price_usd_approx, pack_size=excluded.pack_size, mass_g=excluded.mass_g, buy_url=excluded.buy_url,
  tags=excluded.tags, compat=excluded.compat, updated_at=now();\n`;
}
sql += "\n";
for (const d of designs) {
  sql += `insert into reference_designs (id,name,url,license,summary,robot_type,drive,autonomy,difficulty,approx_cost_usd,best_for,similar_part_ids) values (${[
    s(d.id), s(d.name), s(d.url), s(d.license), s(d.summary), s(d.robot_type), s(d.drive), s(d.autonomy),
    s(d.difficulty), intArr(d.approx_cost_usd), arr(d.best_for), arr(d.similar_part_ids),
  ].join(",")})
on conflict (id) do update set name=excluded.name, url=excluded.url, license=excluded.license, summary=excluded.summary,
  robot_type=excluded.robot_type, drive=excluded.drive, autonomy=excluded.autonomy, difficulty=excluded.difficulty,
  approx_cost_usd=excluded.approx_cost_usd, best_for=excluded.best_for, similar_part_ids=excluded.similar_part_ids;\n`;
}
sql += "\ncommit;\n";

writeFileSync(join(root, "supabase/seed.sql"), sql);
console.log(`seed.sql: ${parts.length} parts, ${designs.length} reference designs`);
